apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
data:
  tx-smtp-relay-host: '{{ .Values.smtp.relayHost }}'
  tx-smtp-relay-myhostname: '{{ .Values.smtp.relayMyhostname }}'
  tx-smtp-relay-username: '{{ .Values.smtp.relayUsername }}'
  tx-smtp-relay-networks: '{{ .Values.smtp.relayNetworks }}'
