apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  tx-smtp-relay-password: {{ .Values.smtp.relayPassword | b64enc }}
