# Default values for postfix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# High availability
replicaCount: 2

# Docker image
image:
  repository: giskou/postfix-relay
  # default tag is the appVersion from Chart.yaml
  tag: ""
  pullPolicy: Always

# Expose pods with service on port 25
service:
  type: ClusterIP
  port: 25

# SMTP server details
# Used by postfix to connect to SMTP server
smtp:
  relayHost: "[smtp.example.com]:25"
  relayMyhostname: example.com
#  relayUsername: relayuser
#  relayPassword: relaypassword
  relayNetworks: '10.244.0.0/16'

# Resources needed for the pods
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

storage:
  storageClassName: ""
  size: '1Gi'
